### ISSUE TITLE
how can I use get_load_video() or convert a cv::Mat of openCV into Cimg?

### ISSUE THREAD

**Issue by Thanh-Binh** [lasote/cimg#1]
I tried to use 
- plugg-in for converting openCV Mat into CImg
- get_load_video()
without any success by building.
Could you please show me a way for solving this problem?
Thanks

**Comment by lasote** [comment]
Sorry, I only opened this repository when I was working in Biicode, company already closed, and I'm not aware of the use of the CImg library, just tried to package it. I suggest to open the issue in the official repository: https://github.com/dtschump/CImg/issues
